### ISSUE TITLE
Issue when trying to build containers for AI Lab recipie

### ISSUE THREAD

**Issue by cedricclyburn** [containers/podman-desktop-extension-ai-lab#1308] opened 2024-06-29 12:51 UTC
### Bug description

Just freshly downloaded the newest version of Podman desktop, and Podman, and tried to use the object detection recipe, but getting an error when trying to build the containers for the specific app

<img width="1393" alt="Screenshot 2024-06-29 at 10 50 07 PM" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/54345140/2fabb056-6f28-4c25-903f-c5f4ac8b6eb1">

```
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-started listeners added. Use emitter.setMaxListeners() to increase limit
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-stopped listeners added. Use emitter.setMaxListeners() to increase limit
error : main ↪️ Kubeconfig path /Users/cclyburn/.kube/config provided does not exist. Skipping.
log : main ↪️ Starting http server to handle webviews on port 44000
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Delayed startup, flushing 5 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Activating extension (podman-desktop.compose) with max activation time of 20 seconds
log : main ↪️ Activating extension (podman-desktop.compose) ended in 3 milliseconds
log : main ↪️ Activating extension (podman-desktop.docker) with max activation time of 20 seconds
log : main ↪️ Activating extension (podman-desktop.docker) ended in 1 milliseconds
log : main ↪️ Activating extension (podman-desktop.kind) with max activation time of 20 seconds
error : main ↪️ [compose] Error getting compose version: Error: Failed to execute command: spawn /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/docker-compose ENOENT
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 539.707834ms
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 430.63316599999985ms
error : main ↪️ [kind] Error: Failed to execute command: spawn kind-darwin-arm64 ENOENT
log : main ↪️ Activating extension (podman-desktop.kind) ended in 1094 milliseconds
log : main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 20 seconds
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ Activating extension (podman-desktop.kube-context) ended in 1 milliseconds
log : main ↪️ Activating extension (podman-desktop.kubectl-cli) with max activation time of 20 seconds
log : main ↪️ Activating extension (podman-desktop.kubectl-cli) ended in 2 milliseconds
log : main ↪️ Activating extension (podman-desktop.lima) with max activation time of 20 seconds
debug : main ↪️ [lima] Could not find socket at /Users/cclyburn/.lima/podman/sock/podman.sock
log : main ↪️ Activating extension (podman-desktop.lima) ended in 1 milliseconds
log : main ↪️ Activating extension (podman-desktop.podman) with max activation time of 20 seconds
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
warn : main ↪️ [kubectl-cli] Error getting kubectl from user PATH: Error: Failed to execute command: spawn kubectl ENOENT, trying from extension storage path
warn : main ↪️ [kubectl-cli] Error getting kubectl version system from extension storage path Error: Failed to execute command: spawn /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.kubectl-cli/bin/kubectl ENOENT
log : main ↪️ Activating extension (podman-desktop.podman) ended in 44 milliseconds
log : main ↪️ Activating extension (podman-desktop.registries) with max activation time of 20 seconds
log : main ↪️ Activating extension (podman-desktop.registries) ended in 0 milliseconds
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting podman-desktop.podman container engine
log : main ↪️ [compose] Made /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/docker-compose executable
log : main ↪️ [compose] Successfully installed 'docker-compose' binary.
log : main ↪️ [kubectl-cli] Made /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.kubectl-cli/bin/kubectl executable
log : main ↪️ [kubectl-cli] Successfully installed 'kubectl' binary.
warn : main ↪️ [podman]  Can't get machine podman-machine-default resource usage error Error: no engine matching this container
trace : main ↪️ [podman] unable to check qemu version Error: Failed to execute command: spawn qemu-system-aarch64 ENOENT
error : main ↪️ Trace: [podman] unable to check qemu version pc [Error]: Failed to execute command: spawn qemu-system-aarch64 ENOENT
    at ChildProcess.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:337:12755)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  exitCode: 1,
  command: 'qemu-system-aarch64',
  stdout: '',
  stderr: '',
  cancelled: false,
  killed: false
}
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:337:21166
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
log : main ↪️ [kind] Made /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.kind/kind-darwin-arm64 executable
log : main ↪️ [kind] Successfully installed 'kind' binary.
log : main ↪️ [kind] kind extension is active
log : main ↪️ [kind] kind extension is active
log : main ↪️ error is Error: socket hang up
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
warn : main ↪️ [podman]  Can't get machine podman-machine-default resource usage error Error: no running provider for the matching container
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
log : main ↪️ error is Error: socket hang up
warn : main ↪️ Error when handling events Error: Error in handling events Will reconnect in 5s Error: Error in handling events
log : main ↪️ Activating extension (podman-desktop.minikube) with max activation time of 20 seconds
error : main ↪️ [minikube] Error: Error: spawn minikube-darwin-arm64 ENOENT
log : main ↪️ Activating extension (podman-desktop.minikube) ended in 1581 milliseconds
log : main ↪️ Activating extension (redhat.bootc) with max activation time of 20 seconds
log : main ↪️ [bootc] starting bootc extension
log : main ↪️ Activating extension (redhat.bootc) ended in 13 milliseconds
log : main ↪️ Activating extension (redhat.ai-lab) with max activation time of 20 seconds
log : main ↪️ [ai-lab] starting AI Lab extension
log : main ↪️ [ai-lab] updated indexHtml to <!DOCTYPE html>
<html class="fixed" lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="http://dc6c0b79-f9ce-4a5d-b7dd-4168e84c90bc.webview.localhost:44000/media/favicon.ico" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0" />
    <title>Podman Desktop</title>
    <script type="module" crossorigin src="http://dc6c0b79-f9ce-4a5d-b7dd-4168e84c90bc.webview.localhost:44000/media/index-CQFX5UdK.js"></script>
    <link rel="stylesheet" crossorigin href="http://dc6c0b79-f9ce-4a5d-b7dd-4168e84c90bc.webview.localhost:44000/media/index-CQlLfpLR.css">
  </head>
  <body class="overflow-hidden text-white">
    <div id="app"></div>
  </body>
</html>

log : main ↪️ Activating extension (redhat.ai-lab) ended in 91 milliseconds
log : main ↪️ Activating extension (redhat.redhat-sandbox) with max activation time of 20 seconds
log : main ↪️ [redhat-sandbox] starting extension openshift-sandbox
log : main ↪️ [redhat-sandbox] Config file location /Users/cclyburn/.kube/config
log : main ↪️ Activating extension (redhat.redhat-sandbox) ended in 3 milliseconds
log : main ↪️ [kind] kind extension is active
log : main ↪️ [minikube] Made /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.minikube/minikube-darwin-arm64 executable
log : main ↪️ [minikube] Successfully installed 'minikube' binary.
log : main ↪️ [minikube] minikube extension is active
log : main ↪️ [kind] kind extension is active
log : main ↪️ [minikube] minikube extension is active
log : main ↪️ [ai-lab] Cloning repository https://github.com/containers/ai-lab-recipes in /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab/object_detection.
log : main ↪️ [ai-lab] Reading configuration from /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab/object_detection/recipes/computer_vision/object_detection/ai-lab.yaml.
warn : main ↪️ [ai-lab] There is no workers compatible. Using default local mounting
log : main ↪️ [ai-lab] Application Manager using context /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab/object_detection/model_servers/object_detection_python for container object-detection-server
log : main ↪️ [ai-lab] Application Manager using context /Users/cclyburn/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab/object_detection/recipes/computer_vision/object_detection/client for container object-detection-client
error : main ↪️ [ai-lab] Something went wrong while trying to start application Error: Context configured does not exist.
log : main ↪️ error in buildImage Error: The operation was aborted
error : main ↪️ [ai-lab] Something went wrong while building the image:  The operation was aborted
error : main ↪️ (node:2383) UnhandledPromiseRejectionWarning: Error: Something went wrong while building the image: AbortError: The operation was aborted
    at /Users/cclyburn/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist/extension.js:7088:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `Podman Desktop --trace-warnings ...` to show where the warning was created)
error : main ↪️ (node:2383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 531)
```

### Operating system

Mac OS Sonoma 14.5

### Installation Method

from Podman-Desktop extension page

### Version

1.0.0

**Comment by benoitf** [comment] 2024-06-29 13:58
could you try to install qemu-system-aarch64 binary (qemu) on the computer as there is an error reported on this binary (just to check if it is changing something)

it says the operation has been aborted (for the build)


you might go using the CLI to the folder being built

might be
```
cd $HOME/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab/object_detection/model_servers/llamacpp_python

 podman build -t foo -f base/Containerfile .
```

**Comment by jeffmaury** [comment] 2024-07-01 16:04
Caused by https://github.com/containers/ai-lab-recipes/issues/504

Closing as it will be closed when we will release a new version of the recipe with the new release of Podman AI Lab

**Closed by jeffmaury** 2024-07-01 16:04 UTC
