### ISSUE TITLE
[UX] Icon for downloaded models is the same as non downloaded ones

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#1409] opened 2024-07-22 09:28 UTC
### Bug description

Maybe related to light mode enablement

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

**Comment by axel7083** [comment] 2024-07-22 13:16
We do not display a difference icon between downloaded and remote as we are using the status to indicate if the model is being used or not.

The change has been included in https://github.com/containers/podman-desktop-extension-ai-lab/issues/791.

![image](https://github.com/user-attachments/assets/372655ba-6835-4bfb-b90c-953aedbdce1b)

Currently this is not a bug, but we could found a way to improve the distinction ?

**Comment by jeffmaury** [comment] 2024-07-22 13:37
> We do not display a difference icon between downloaded and remote as we are using the status to indicate if the model is being used or not.
> 
> The change has been included in #791.
> 
> ![image](https://private-user-images.githubusercontent.com/42176370/350977473-372655ba-6835-4bfb-b90c-953aedbdce1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTQ5MjEsIm5iZiI6MTcyMTY1NDYyMSwicGF0aCI6Ii80MjE3NjM3MC8zNTA5Nzc0NzMtMzcyNjU1YmEtNjgzNS00YmZiLWI5MGMtOTUzYWVkYmRjZTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEzMjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYmJiZjk5MGEzNmYxNzdmMDJiYTc3N2VmMGI0YjE2YjU2MTVlZTBiZDhjYzU3Y2JkYzIxNDIwYzFhZTdlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H4gxDhw0PFgtTbgIOOwlwLsVJzjPnzAnuBekgyp-eIo)
> 
> Currently this is not a bug, but we could found a way to improve the distinction ?

That's due to a change of the semantic as the icon was solid for downloaded models and it's now solid for in use models

**Comment by MariaLeonova** [comment] 2024-08-21 08:47
What about these 2 options on the left for the downloaded models? 
![Screenshot 2024-08-21 at 10 46 21](https://github.com/user-attachments/assets/89c76e50-d3af-443f-96bd-f18642431a4d)

**Comment by jeffmaury** [comment] 2024-08-21 10:48
> What about these 2 options on the left for the downloaded models? ![Screenshot 2024-08-21 at 10 46 21](https://private-user-images.githubusercontent.com/14108590/359823311-89c76e50-d3af-443f-96bd-f18642431a4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzcwMzUsIm5iZiI6MTcyNDIzNjczNSwicGF0aCI6Ii8xNDEwODU5MC8zNTk4MjMzMTEtODljNzZlNTAtZDNhZi00NDNmLTk2YmQtZjE4NjQyNDMxYTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEwMzg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZDNjOTIwY2Y5ZTUzZDk0ODQ3NWVjYzRhYTBjNTgwZDdhN2Y3YjRjZTYwYWRhMTVmY2JlZmQwZDIzM2ZhYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qd3b_T8Go0kZmTBS0Q5wwIQu227z-ANDKUKKk78mihE)

White background = downloaded green bullet = in use ?

**Comment by MariaLeonova** [comment] 2024-08-21 11:51
so those are both suggestions for the downloaded models. I was looking at some penpot files with Emma, and these two options came to mind: 
![Screenshot 2024-08-21 at 13 49 33](https://github.com/user-attachments/assets/c6bc1683-67cc-46ec-9751-a2c8d53dba48)

I'll lay them out to be more clear.

**Comment by MariaLeonova** [comment] 2024-08-21 11:57
![rect166](https://github.com/user-attachments/assets/bee027fe-e309-41b0-828e-32c82fe18420)

**Comment by slemeur** [comment] 2024-08-21 12:05
I like the idea of using the down arrow to indicated it's downloaded. should the arrow be green, to show reinforce even more that "yes it's downloaded"

**Comment by jeffmaury** [comment] 2024-08-21 13:02
Please don't forget it should be aligned with Images and Volumes icons on Podman Desktop core

**Comment by ekidneyrh** [comment] 2024-08-21 15:14
> Please don't forget it should be aligned with Images and Volumes icons on Podman Desktop core

Not sure what you mean by this @jeffmaury?

I like the arrow one! Idk about having it green tho - something about green makes me think of active / running? maybe that's just me tho

**Comment by jeffmaury** [comment] 2024-08-21 18:53
> > Please don't forget it should be aligned with Images and Volumes icons on Podman Desktop core
> 
> Not sure what you mean by this @jeffmaury?
> 
> I like the arrow one! Idk about having it green tho - something about green makes me think of active / running? maybe that's just me tho 

When a volume or image is used by a running container its icon is also having a green background

**Comment by MariaLeonova** [comment] 2024-08-22 12:24
Ok, so shall we agree on this one for the downloaded model that's not currently in use? 
![Screenshot 2024-08-22 at 14 23 50](https://github.com/user-attachments/assets/fb933bac-0bbf-4720-9ad5-25e857b21861)

**Comment by axel7083** [comment] 2024-08-26 07:35
Hey @MariaLeonova I just came back from PTO, so here is my feedback / impressions.

First thanks for the design, I really like the ideas of the top right icon. 

When I saw the `Arrow down` icon I feel like it is an action, and my first intuition was the contrary of what you are stating, having the `Arrow down` icon feels like it is not downloaded. 

# Implementation wise

The top right icon does not seems to be customizable, this would require a change in the PD ui library. 

# Icons usage

Let's look at some examples in PD and outside for similar elements having those download/downloaded states.

## Extension Catalog in PD

![image](https://github.com/user-attachments/assets/2484845d-ad84-457c-9170-184d00903c95)

We are not showing the arrow/download icon when the state is downloaded, we seems to prefer the [circle-check](https://fontawesome.com/icons/circle-check?f=classic&s=solid).

## LM Studio 

Screenshot provided by @slemeur 

![image](https://github.com/user-attachments/assets/5b7d6d10-253c-4e63-bec5-e0143c2f4464)

We also have some similar icons for the different states. 

## AI Lab

We are trying to have a similar design than the extensions card from PD

![image](https://github.com/user-attachments/assets/4e64e171-54e7-43e4-b408-b999b80249c9)

**Comment by MariaLeonova** [comment] 2024-08-29 11:54
@axel7083 thank you for such a detailed comment! With my suggestion I was following the logic of how the model status is currently displayed (eg running vs not sunning) However, I am not at all opposed to your suggestion to indicate the status with a separate icon altogether. If I consider options similar to the examples you've provided, that would be a checkmark icon next to the model name or alternatively, the download button will change to indicate the fact that the action has been completed. 

In which case, these could be 2 potential places to indicate the downloaded model:
![Screenshot 2024-08-29 at 13 53 44](https://github.com/user-attachments/assets/6d96ac43-262e-444c-86b3-d0fccc47d2fe)
WDYT?

**Comment by MariaLeonova** [comment] 2024-09-04 11:23
Given that the Download button gets replaced by a Delete button once the model is downloaded and it's not an action, I would suggest placing the indication elsewhere. 
![Screenshot 2024-09-04 at 13 19 23](https://github.com/user-attachments/assets/e7741ee6-df80-44d8-be10-94a7b40c3baa)

For now my two suggestions are:

- follow the pattern of model statuses and add an arrow to the icon next to the model
- add a checkmark icon next to model name 

![downloaded model](https://github.com/user-attachments/assets/d752720f-33aa-480b-a083-2264502692df)

That said, it might be beneficial to list all potential model statuses and decide how to represent them in the model catalog.

**Comment by axel7083** [comment] 2024-09-04 12:08
> WDYT?

Hi @MariaLeonova  ! Sorry I did not replied, the notification for the first message was lost while I was in PTO.

> - follow the pattern of model statuses and add an arrow to the icon next to the model

I like this idea, it would allow for a quick read to differentiate downloaded and non-downloaded

>  - add a checkmark icon next to model name

I am afraid of this one as the color and icon would feel "too much" as it would probably be shown in many lines when a lot of models would have been downloaded.

---

I would like to know if we could have another example, you will probably have a better vision on the implication and logic from an user POV: in podman desktop we have a few icons for the PVC, and there is one with dashes line 

![image](https://github.com/user-attachments/assets/4931d4ac-446f-4519-a41f-ff8ce57b2d1c)

![image](https://github.com/user-attachments/assets/3df75155-700e-4cc8-9d18-9d84fbaa5dcf)

I don't have any skills for illustration so I can't illustrate what I think, but I am wondering if it would make sense to have a dashed version of the model icon to illustrate it is not downloaded, like "incomplete"

**Comment by MariaLeonova** [comment] 2024-09-05 08:48
@axel7083 do any of the bottom ones look good to you? 
![Screenshot 2024-09-05 at 10 47 28](https://github.com/user-attachments/assets/0dfb15c4-4c53-4593-ab2a-f19c0a737ab7)

**Comment by axel7083** [comment] 2024-09-05 08:54
![image](https://github.com/user-attachments/assets/c7845fe7-6889-428a-a203-8af3f59c8c2a)

I really like this one !

**Comment by ekidneyrh** [comment] 2024-09-05 09:41
> I really like this one !

+1 for this one too :) I think it works well with how we display status/different states across the app. Love the comment Axel made about it being 'incomplete' hence not downloaded

**Comment by MariaLeonova** [comment] 2024-09-05 10:17
If we are all in agreement, here are the source files: 
![download-icon-darkbg](https://github.com/user-attachments/assets/3a8a4107-c7b4-488a-b164-1916dcb4065b)
![download-icon-lightbg](https://github.com/user-attachments/assets/c04d7c2c-bb8d-4a7b-9274-6ac9444e41f1)
![downloaded-icon-darkbg](https://github.com/user-attachments/assets/301f1b70-e514-4296-a802-8b7785b9a9ea)
![downloaded-icon-lightbg](https://github.com/user-attachments/assets/b42811fd-ee86-4e6e-a989-dfe09d9e3842)
![downloaded-icon](https://github.com/user-attachments/assets/12e524cc-3163-4738-8c10-7b041dbfb3eb)

**Comment by slemeur** [comment] 2024-09-05 12:11
This is heading into the right direction.
I'm just wondering if the "dotted" line is really conveying the message we are looking for. I'd suggest we add the "down arrow" on it. What do you think?

**Comment by axel7083** [comment] 2024-09-05 12:37
> This is heading into the right direction. I'm just wondering if the "dotted" line is really conveying the message we are looking for. I'd suggest we add the "down arrow" on it. What do you think?

I think this would overload the screen with too many icons, we already have a difference with the action buttons.

![image](https://github.com/user-attachments/assets/2ecd05f4-ee38-4d42-a95d-88c68a95791b)

Adding a custom icon is already one step extra, adding a custom download icon would be one more step again.

---

Implementation wise we would need to update the podman-desktop ui library to support custom icon at the top right as currently it is not

**Comment by MariaLeonova** [comment] 2024-09-10 09:52
@slemeur this is what it would look like with an arrow:
![Screenshot 2024-09-10 at 11 52 06](https://github.com/user-attachments/assets/b1a1ee58-c5cf-4a02-a79f-376bdd3a80fc)

**Comment by MariaLeonova** [comment] 2024-09-30 08:07
@jeffmaury @axel7083 This has been pending for 3 weeks, let's make a decision?

**Comment by axel7083** [comment] 2024-09-30 10:38
@MariaLeonova let's go with the following

![image](https://github.com/user-attachments/assets/667dec94-dfe3-4704-a019-9d68952aa0ed)

Can you upload the svg file in this issue ?

**Comment by MariaLeonova** [comment] 2024-09-30 11:39
@axel7083 I think they are all here: https://github.com/containers/podman-desktop-extension-ai-lab/issues/1409#issuecomment-2331150379

**Comment by axel7083** [comment] 2024-10-07 08:59
Closing as the implementation will be tracked by https://github.com/containers/podman-desktop-extension-ai-lab/issues/1848, thanks @MariaLeonova

**Closed by axel7083** 2024-10-07 08:59 UTC
